@Panda.API_HostAddress = https://localhost:7253

###

POST {{Panda.API_HostAddress}}/api/patients
Content-Type: application/json

{
  "nhsNumber": "1685807151", 
  "name": "Jeffrey Young3", 
  "dateOfBirth": "1963-08-27", 
  "postcode":"WA55 8HE"
}

###

@nhsNumber=1685807151
GET {{Panda.API_HostAddress}}/api/patients/{{nhsNumber}}

###

PUT {{Panda.API_HostAddress}}/api/patients/{{nhsNumber}}
Content-Type: application/json
{
  "nhsNumber": "1991326211", 
  "name": "Jeffrey Young not any more", 
  "dateOfBirth": "1963-08-27", 
  "postcode":"WA55 8HE"
}

###

DELETE {{Panda.API_HostAddress}}/api/patients/{{nhsNumber}}

###

POST {{Panda.API_HostAddress}}/api/appointments
Content-Type: application/json

{
    "patient": "0240288238",
    "status": "active",
    "time": "2025-07-16T13:00:00+01:00",
    "duration": "1h30m",
    "clinician": "Dr Jordan Lewis",
    "department": "orthopaedics",
    "postcode": "CW6E 2ET",
    "id": "c455638f-99aa-478a-82bc-fd76da4991f8"
  }

###

@Id=c455638f-99aa-478a-82bc-fd76da4991f8
GET {{Panda.API_HostAddress}}/api/appointments/{{Id}}

###

PUT {{Panda.API_HostAddress}}/api/appointments/{{Id}}
Content-Type: application/json

{
  "patient": "0240288238", 
  "status": "Active", 
  "time": "2018-01-21T16:30:00+00:00", 
  "duration": "15m", 
  "clinician": "Jason Holloway", 
  "department": "oncology",
  "postcode": "UB56 7XQ",
  "id":"c455638f-99aa-478a-82bc-fd76da4991f8"
}

###
